import type sanitizeHtml from 'sanitize-html';

export const sanitizeOptions: sanitizeHtml.IOptions = {
  allowedTags: [
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'p',
    'div',
    'br',
    'hr',
    'strong',
    'b',
    'em',
    'i',
    'u',
    's',
    'strike',
    'blockquote',
    'ol',
    'ul',
    'li',
    'a',
    'img',
    'video',
    'iframe',
    'figure',
    'figcaption',
    'span',
  ],
  allowedAttributes: {
    'a': ['href', 'name', 'target', 'rel'],
    'img': ['src', 'alt', 'width', 'height', 'loading'],
    'iframe': [
      'src',
      'width',
      'height',
      'frameborder',
      'allow',
      'allowfullscreen',
    ],
    'video': ['src', 'controls', 'width', 'height'],
    '*': ['style'],
  },
  allowedSchemesByTag: {
    img: ['http', 'https', 'data'],
    a: ['http', 'https', 'mailto'],
    iframe: ['http', 'https'],
    video: ['http', 'https', 'data'],
  },
  allowProtocolRelative: true,
  allowedStyles: {
    '*': {
      'color': [/^.*$/],
      'background-color': [/^.*$/],
      'text-align': [/^left$|^right$|^center$|^justify$/],
      'float': [/^left$|^right$/],
      'width': [/^\d+(?:px|%)?$/],
      'height': [/^\d+(?:px|%)?$/],
    },
    'span': {
      'color': [/^.*$/],
      'background-color': [/^.*$/],
    },
    'img': {
      width: [/^\d+(?:px|%)?$/],
      height: [/^\d+(?:px|%)?$/],
    },
  },
  transformTags: {
    b: 'strong',
    i: 'em',
  },
};
